<a href="https://colab.research.google.com/github/fallcat/ml-notes/blob/master/decision_boundary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

def distanceFunc(metric_type, vec1, vec2):
    """
    Computes the distance between two d-dim vectors
    Args:
        metric_type: String
        vec1 (numpy vector): Vector
        vec2 (numpy vector): Vector
    Returns:
        distance (float): distance between the two vectors
    """

    diff = vec1 - vec2
    if metric_type == "L0":
        distance = np.sum(diff!=0)

    if metric_type == "L1":
        distance = np.sum(np.abs(diff))

    if metric_type == "L2":
        distance = np.sqrt(np.sum(diff**2))
        
    if metric_type == "L-inf":
        distance = np.max(np.abs(diff))
        
    return distance


In [20]:
def get_decision_boundaries(metric_type):
    x = [[1,4], [5,1]]
    o = [[4,4]]
    x = np.array(x)
    o = np.array(o)
    a = np.linspace(0,6,13)
    b = np.linspace(0,6,13)
    arr = np.zeros((13,13))
    for i, a_ in enumerate(a):
        for j, b_ in enumerate(b):
            temp = np.array([a_,b_])
            x_min = 100
            o_min = 100
            for x_ in x:
                x_tmp = distanceFunc(metric_type, temp, x_)
                # print("x_tmp", x_tmp)
                if x_tmp < x_min:
                    x_min = x_tmp
            for o_ in o:
                o_tmp = distanceFunc(metric_type, temp, o_)
                # print("o_tmp", o_tmp)
                if o_tmp < o_min:
                    o_min = o_tmp
            if x_min > o_min:
                arr[i, j] = 1
            elif x_min < o_min:
                arr[i, j] = -1
    return arr

In [21]:
for metric in ["L0", "L1", "L2", "L-inf"]:
    arr = get_decision_boundaries(metric)
    print(metric)
    print(arr.T[::-1])

L0
[[ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  0. -1. -1. -1. -1.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0. -1.  0.  0.]]
L1
[[-1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [-